# Generated by Django 5.1.7 on 2025-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/user_profile'),
        ),
    ]
